"""task create model and relation update

Revision ID: 04cd786822a1
Revises: fb6554febdbb
Create Date: 2025-02-11 14:58:47.236255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '04cd786822a1'
down_revision: Union[str, None] = 'fb6554febdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('assigned_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_ibfk_1', 'task', type_='foreignkey')
    op.drop_constraint('task_ibfk_2', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'user', ['assigned_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('task', 'assigned_by_manager_id')
    op.drop_column('task', 'assigned_by_team_lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assigned_by_team_lead_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('assigned_by_manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_2', 'task', 'user', ['assigned_by_team_lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('task_ibfk_1', 'task', 'user', ['assigned_by_manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('task', 'assigned_by_id')
    op.drop_column('task', 'created_by_id')
    # ### end Alembic commands ###
