"""populate create tl and employee

Revision ID: 1749a8f363b2
Revises: 04cd786822a1
Create Date: 2025-02-12 13:58:27.520480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from simple_crud_api.utils.user import UserType


# revision identifiers, used by Alembic.
revision: str = '1749a8f363b2'
down_revision: Union[str, None] = '04cd786822a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

password = '$2b$12$YeLRhMXRdQSSGR/1habVxuj70ZM/czLGguWnGvMG66MIh5M9Lh99C'
employee = [
    ('employee1', 'employee1@gmail.com', password),
    ('employee2', 'employee2@gmail.com', password),
    ('employee3', 'employee3@gmail.com', password),
    ('employee4', 'employee4@gmail.com', password),
    ('employee5', 'employee5@gmail.com', password)
]
team_lead = [
    ('teamlead1', 'teamlead1@gmail.com', password),
    ('teamlead2', 'teamlead2@gmail.com', password),
    ('teamlead3', 'teamlead3@gmail.com', password)
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for d in employee:
        op.execute("INSERT INTO user (username, email, password) values ('{}', '{}', '{}')".format(d[0], d[1], d[2]))
        op.execute("UPDATE user SET active = 1 WHERE username = '{}'".format(d[0]))
        op.execute("UPDATE user SET role = '{}' WHERE username = '{}'".format(UserType.Employee.name, d[0]))
        
    for d in team_lead:
        op.execute("INSERT INTO user (username, email, password) values ('{}', '{}', '{}')".format(d[0], d[1], d[2]))
        op.execute("UPDATE user SET active = 1 WHERE username = '{}'".format(d[0]))
        op.execute("UPDATE user SET role = '{}' WHERE username = '{}'".format(UserType.TeamLead.name, d[0]))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
