"""account activation column

Revision ID: a2363362fa88
Revises: cf2651a2ca6a
Create Date: 2025-02-07 15:13:51.574925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2363362fa88'
down_revision: Union[str, None] = 'cf2651a2ca6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_activation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_activation')
    # ### end Alembic commands ###
