"""user type to user role

Revision ID: cf2651a2ca6a
Revises: f0e8101e1d5e
Create Date: 2025-02-06 11:15:23.834035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf2651a2ca6a'
down_revision: Union[str, None] = 'f0e8101e1d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='vendor')
    op.drop_table('vendor')
    op.add_column('user', sa.Column('role', sa.Enum('Employee', 'TeamLead', 'Manager', name='usertype'), nullable=True))
    op.drop_column('user', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', mysql.ENUM('Employee', 'TeamLead', 'Manager'), nullable=True))
    op.drop_column('user', 'role')
    op.create_table('vendor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'vendor', ['username'], unique=True)
    # ### end Alembic commands ###
