"""task model update: body and description

Revision ID: fb6554febdbb
Revises: ab58266ed2d8
Create Date: 2025-02-10 16:02:20.626312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb6554febdbb'
down_revision: Union[str, None] = 'ab58266ed2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('task', sa.Column('body', sa.String(length=2000), nullable=True))
    op.drop_column('task', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('task', 'body')
    op.drop_column('task', 'description')
    # ### end Alembic commands ###
